### ISSUE TITLE
Please I need some help

### ISSUE THREAD

**Issue by throwawaygithubaccount1234** [matja/bitcoin-tool#10]
Hi, thanks for creating tool, I'm really thankful.
I'm currently using it to generate a large amount of keys and it's taking a very long time because I'm loading a text file from a shell script and piping the hex output to bitcoin-tool 's input parameter. 
It's taking it over 3 days to generate 100 million keys. 
Would it be possible to modify this to load a large text file into memory and process it line by line?

Please help, I would have no problem offering some donation for your time. 
I couldn't find the contact info in your profile. 
Best regards.

**Comment by matja** [comment]
Thanks for the great suggestion, it was a feature which I've been planning for some time :)

I've created a new branch 'batch-mode' from commit fefd712d83ace0d4631ab7ffd8192da8de1fa080 which hopefully does what you'd like.

It has a new option `--batch`.  Specify this option with the `--input-file` option and it will process all lines in that file.  If your input is not line-delimited, but is perhaps one large piece of binary data which needs to be split into records, then reply to this issue and I'll see what other command-line options are needed.

This is faster than spawning a new process from a shell script for each line in the input, but not as much as I'd hoped for - I get about 6x speedup.  I suspect that the overhead of the EC point multiply is dominating the processing time.

Here's an example using 1000 hex keys in a file :

**Generate 1000 hex private keys**
`keys=1000 ; openssl rand $[32*keys] | xxd -p -c32 > hexkeys`

**Convert without batch mode (shell script)**
```
$ time ( for key in $(cat hexkeys) ; do
./bitcoin-tool --input-format hex --input "$key" --input-type private-key \
--output-type address --network bitcoin --public-key-compression compressed \
--output-format base58check ; done ) > /dev/null
real    0m2.746s
user    0m0.350s
sys     0m0.167s
```

**Convert with batch mode**
```
$ time ./bitcoin-tool \
--batch \
--input-file hexkeys \
--input-format hex \
--input-type private-key \
--network bitcoin \
--public-key-compression compressed \
--output-type address \
--output-format base58check > /dev/null
real    0m0.441s
user    0m0.440s
sys     0m0.000s
```

You can of course pipe directly into bitcoin-tool like so :
`openssl rand $[32*keys] | xxd -p -c32 | bitcoin --input-file - ` ...
With '-' to specify standard input.

**Comment by matja** [comment]
After some futher investigation with perf, it does look like that the EC point multiplication inside OpenSSL is the bottleneck now :
```
  35.23%  bitcoin-tool  libcrypto.so.1.0.0  [.] bn_mul_mont
  12.40%  bitcoin-tool  libcrypto.so.1.0.0  [.] BN_usub
   4.07%  bitcoin-tool  libcrypto.so.1.0.0  [.] BN_mod_mul_montgomery
   3.40%  bitcoin-tool  libcrypto.so.1.0.0  [.] bn_add_words
   2.98%  bitcoin-tool  libcrypto.so.1.0.0  [.] BN_lshift
   2.80%  bitcoin-tool  libcrypto.so.1.0.0  [.] BN_ucmp
   2.77%  bitcoin-tool  libcrypto.so.1.0.0  [.] BN_mod_lshift_quick
   2.54%  bitcoin-tool  libcrypto.so.1.0.0  [.] BN_rshift1
   2.51%  bitcoin-tool  libcrypto.so.1.0.0  [.] BN_uadd
   2.28%  bitcoin-tool  libcrypto.so.1.0.0  [.] BN_lshift1
   2.04%  bitcoin-tool  libcrypto.so.1.0.0  [.] BN_cmp
   2.03%  bitcoin-tool  libcrypto.so.1.0.0  [.] BN_num_bits_word
   2.03%  bitcoin-tool  libcrypto.so.1.0.0  [.] BN_set_word
```

**Comment by throwawaygithub12345** [comment]
Thanks for the quick reply, I love you man. 
Is there a file size limit to the batch mode? 
Have you thought about porting your code to OpenCL? 
I was looking at vanitygen, maybe something in there can help. 

Also, please let me know which address donation can be sent to. 
Really appreciate your work.

**Comment by matja** [comment]
There is no file size limit - the input file is read a line at a time, so it should not use any extra memory.  

You're right that OpenCL would give a big win in the key generation time, the vanitygen code is really nice and I might look for some ideas there.  I will add this to the TODO list!

It seems the batch mode works quite well so I will merge it to the master branch and update the README.md later.

I'd be interested to hear any other feature suggestions you might have :)
Thanks for your offer of a donation, I have created a donation address for this project and I will update the front page later - it is `1KPu5w2fYvwmz1WVpBRaMoSptGWb8hUKAB`

**Comment by throwawaygithub12345** [comment]
If the input is read line by line, is the speed improvement due to not having to start bitcoin-tool a gazillion time? 
I would be interested to know how much improvement there would be if the file is loaded into memory.
It would probably be more challenging to implement. I don't know much about lower level memory management, but even if you had enough RAM, wouldn't you run into problems trying to allocate a big chunk of continuous memory? 

I made some effort to improve the speed by loading the file into a temporary variable in bash and feeding it to a loop, but it had trouble dealing with large files even though there was plenty of RAM.
The OS just would not let bash allocate that much memory. 

Vanitygen is a real piece of gem. Unfortunately, the code is beyond my league.  Please look into porting this to OpenCL. 

Do you think this is even possible? I'm not sure what vanitygen is doing under the hood, but is it starting from a 256 bit hex just like bitcoin-tool?

**Comment by matja** [comment]
I'd done some testing with perf and it seems the I/O overhead is very small (much less than 1%) compared to the key generation.  If the key generation was more than 100x faster then I'd look at reading the input a few MB at a time, or mmap()'ing chunks at a time.

You can load the input file into a ramdisk easily on Linux with `mkdir ramdisk ; mount -t tmpfs tmpfs ramdisk ; cp input ramdisk/` and then run bitcoin-tool from there.  It still means that the libc stdio functions are being used, but they can handle a few GB/s of I/O even on a modest machine.

If bitcoin-tool allocated a big chunk of memory itself then it doesn't need to be contiguous physical memory, nor can it even tell, since the virtual memory manager in the OS transparently handles mapping the pages of noncontiguous physical memory to contiguous virtual address space in the process.

vanitygen starts at an initial random private key, but the way elliptic curve public key generation works means that it can employ a trick of stepping through successive keys by doing a single EC point addition to get each public key.  It still has to convert the internal public key representation into the affine co-ordinate system and then convert to base58 (it can skip the SHA-256 required for base58check if it's only matching characters at the start of the address), but this avoids having to do the expensive EC point multiplication for every private key.

Unfortunately bitcoin-tool cannot use this trick because it cannot assume that the input private keys are consecutive, but there are other optimisations in vanitygen which should be usable.
